- name: Apply patient service
  environment:
#    KUBECONFIG: /home/administrator/.kube/config
  KUBECONFIG: "{{ kubeconfig_path}}"
  command: kubectl apply -f {{ playbook_dir }}/Kubernetes/patient.yml


# testing upgrade