---
- name: Apply Kubernetes manifests from the Kubernetes folder
  hosts: localhost
  become: false
  tasks:
    - name: Apply pvc
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/pvc.yml

    - name: Apply mysql config
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/mysql-config.yml

    - name: Apply mysql
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/mysql.yml

    - name: Apply eureka
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/eureka.yml

    - name: Apply rabbitmq
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/rabbitmq.yml

    - name: Apply patient service
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/patient.yml

    - name: Apply doctor service
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/doctor.yml

    - name: Apply appointment service
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/appointment.yml

    - name: Apply notification service
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/notification.yml

    - name: Apply gateway
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/gateway.yml

    - name: Apply ingress
      command: kubectl apply -f {{ playbook_dir }}/Kubernetes/healthcare-ingress.yaml
