apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: nakulsiwach/appointment-service:v3
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_APPLICATION_NAME
              value: appointmentservice
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/appointmentdb
            - name: eureka.client.service-url.defaultZone
              value: http://eureka:8761/eureka
#            - name: SPRING_RABBITMQ_HOST
#              value: rabbitmq
#            - name: SPRING_RABBITMQ_PORT
#              value: "5672"
#            - name: SPRING_RABBITMQ_USERNAME
#              value: guest
#            - name: SPRING_RABBITMQ_PASSWORD
#              value: guest

---
apiVersion: v1
kind: Service
metadata:
  name: appointment
spec:
  type: ClusterIP  # 👈 Makes service externally accessible
  selector:
    app: appointment
  ports:
    - port: 8083
      targetPort: 8083
