apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: nakulsiwach/appointment-service:v1
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/appointmentdb
            - name: eureka.client.service-url.defaultZone
              value: http://eureka:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: appointment
spec:
  selector:
    app: appointment
  ports:
    - port: 8083
