apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctorservice
  template:
    metadata:
      labels:
        app: doctorservice
    spec:
      containers:
        - name: doctor
          image: nakulsiwach/doctor-service:v3
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_NAME
              value: doctorservice
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/doctordb
            - name: EUREKA_INSTANCE_HOSTNAME
              value: doctorservice
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: eureka.client.service-url.defaultZone
              value: http://eureka:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: doctorservice  # Change this to DOCTORSERVICE
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8082"

spec:
  type: ClusterIP
  selector:
    app: doctorservice
  ports:
    - port: 8082
      targetPort: 8082