apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
        - name: doctor
          image: nakulsiwach/doctor-service:v1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/doctordb
            - name: eureka.client.service-url.defaultZone
              value: http://eureka:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: doctor
spec:
  selector:
    app: doctor
  ports:
    - port: 8082
